package:
    name:           asset-packagist.dev
    homepage:       http://asset-packagist.org/
    namespace:      hiqdev\sites\assetpackagistdev

hisite:
    vhost:
        domain:     dev.asset-packagist.org

deploy:
    before:
        - nginx/deploy
