package:
    name:           asset-packagist.dev
    homepage:       http://asset-packagist.org/
    namespace:      hiqdev\assetpackagistsite

hisite:
    vhost:
        ip: 127.0.0.1

deploy:
    before:
        - nginx/deploy
